name: Test riogisoffline plugin

on:
  push:
    branches:
      - "**"
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-tags }}
    strategy:
      matrix:
        include:
          - qgis-tags: latest
            pipcmd: --break-system-packages
          - qgis-tags: release-3_34
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4
      - name: update host image
        run: |
          # Add Docker's official GPG key:
          apt-get update
      - name: Run tests on host image
        run: |
          pip install -qr ./test_riogisoffline/requirements.test.txt ${{ matrix.pipcmd }}
          python3 -m pytest ./test_riogisoffline --cov --cov-report=xml:coverage.xml
          ls -R
        
      # Upload coverage report. Will not work if the repo is private
      - name: Upload coverage to Codecov
        if: ${{ matrix.qgis-tags == 'latest' && !github.event.repository.private }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: pytest
          fail_ci_if_error: false # set to true when upload is working
          verbose: false

  #code-style:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/setup-python@v4
  #    - uses: pre-commit/action@v3.0.0
