name: Test riogisoffline plugin

on:
  push:
    branches:
      - "**"
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-tags }}
    strategy:
      matrix:
        qgis-tags: [ release-3_28, release-3_34, latest ]
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        run: apt-get install docker
      - name: Pull qgis image
        run: docker pull qgis/qgis:${{ matrix.qgis-tags }}
   
      - name: Run tests
        env:
          QGIS_IN_CI: 1
        run: docker run --rm --net=host --volume `pwd`:/app -w=/app qgis/qgis:${{ matrix.qgis-tags }} sh -c "python3 -m pip install -qr /app/test_riogisoffline/requirements.test.txt && xvfb-run -s '+extension GLX -screen 0 1024x768x24' pytest -v --cov=/app/riogisoffline --cov-report=xml /app/test_riogisoffline"

      # Upload coverage report. Will not work if the repo is private
      - name: Upload coverage to Codecov
        if: ${{ matrix.qgis-tags == 'latest' && !github.event.repository.private }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: pytest
          fail_ci_if_error: false # set to true when upload is working
          verbose: false

  #code-style:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/setup-python@v4
  #    - uses: pre-commit/action@v3.0.0
